#!/bin/bash
#
# Failure Notification Email Script
# Sends detailed validation failure report
#

set -euo pipefail

FAILURE_STAGE="$1"
FAILURE_DETAILS="$2"
LOG_FILE="$3"
RECIPIENT="${4:-apurva.garware@gmail.com}"

DATE=$(date '+%Y-%m-%d')
TIMESTAMP=$(date '+%A, %B %d, %Y %I:%M %p %Z')
NOTIFICATION_FILE="/tmp/failure-notification-$DATE-$$.md"

# Extract validation logs if available
COS_VALIDATION_LOG=""
MARKET_VALIDATION_LOG=""
WORKFLOW_VALIDATION_LOG=""

if [ -f "$LOG_FILE" ]; then
    # Extract CoS validation section
    COS_VALIDATION_LOG=$(sed -n '/CoS brief for hallucinations/,/VALIDATION SUMMARY/p' "$LOG_FILE" 2>/dev/null || echo "")

    # Extract Market Intel validation section
    MARKET_VALIDATION_LOG=$(sed -n '/Market Intel for hallucinations/,/VALIDATION SUMMARY/p' "$LOG_FILE" 2>/dev/null || echo "")

    # Extract Workflow validation section
    WORKFLOW_VALIDATION_LOG=$(sed -n '/WORKFLOW-VALIDATOR.*Starting/,/WORKFLOW VALIDATION SUMMARY/p' "$LOG_FILE" 2>/dev/null || echo "")
fi

# Build the notification email
cat > "$NOTIFICATION_FILE" <<'HEADER'
# ⚠️ Daily COS Agent - VALIDATION FAILED

---

HEADER

cat >> "$NOTIFICATION_FILE" <<EOF
**Date:** $TIMESTAMP
**Status:** ❌ FAILED
**Stage:** $FAILURE_STAGE

---

## Failure Summary

$FAILURE_DETAILS

---

## Validation Results

EOF

# Add CoS Brief validation results if available
if [ -n "$COS_VALIDATION_LOG" ]; then
    cat >> "$NOTIFICATION_FILE" <<EOF

### 📋 CoS Brief Validation

\`\`\`
$COS_VALIDATION_LOG
\`\`\`

EOF
else
    cat >> "$NOTIFICATION_FILE" <<EOF

### 📋 CoS Brief Validation

✅ Passed (or not reached)

EOF
fi

# Add Market Intel validation results if available
if [ -n "$MARKET_VALIDATION_LOG" ]; then
    cat >> "$NOTIFICATION_FILE" <<EOF

### 📊 Market Intel Validation

\`\`\`
$MARKET_VALIDATION_LOG
\`\`\`

EOF
else
    cat >> "$NOTIFICATION_FILE" <<EOF

### 📊 Market Intel Validation

Not reached or data unavailable

EOF
fi

# Add Workflow validation results if available
if [ -n "$WORKFLOW_VALIDATION_LOG" ]; then
    cat >> "$NOTIFICATION_FILE" <<EOF

### 🔄 Workflow Validation

\`\`\`
$WORKFLOW_VALIDATION_LOG
\`\`\`

EOF
fi

# Add recent log excerpt
cat >> "$NOTIFICATION_FILE" <<EOF

---

## Recent Log Excerpt

\`\`\`
$(tail -50 "$LOG_FILE" 2>/dev/null || echo "Log file not available")
\`\`\`

---

## What This Means

The daily brief generation failed one or more validation checks. Common causes:

1. **Hallucinated Content** - Claude invented news stories or calendar events not in source data
2. **Data Quality Issues** - Source APIs (Google Calendar, NewsAPI) returned incomplete data
3. **URL Mismatch** - News URLs don't match NewsAPI source (likely hallucination)
4. **Missing Events** - Calendar events in source data missing from brief
5. **Format Errors** - Brief structure doesn't match expected template

## Next Steps

1. Review the validation logs above to identify which checks failed
2. Check the full log file: \`$LOG_FILE\`
3. Manually verify source data quality (Google Calendar, NewsAPI)
4. Re-run the orchestrator if this was a transient issue: \`cd ~/cos-agent && ./orchestrator.sh\`

## Log File Location

Full logs available at: \`$LOG_FILE\`

---

**Automated validation system prevented potentially inaccurate brief from being sent.**

Generated by COS Agent Validation System
$TIMESTAMP

EOF

# Send the notification email
SEND_EMAIL_SCRIPT="$HOME/.claude/skills/chief-of-staff-orchestrator/send-email.sh"

if [ -f "$SEND_EMAIL_SCRIPT" ]; then
    echo "Sending failure notification to $RECIPIENT..."
    if "$SEND_EMAIL_SCRIPT" "$NOTIFICATION_FILE" "$RECIPIENT" "⚠️ COS Agent Validation FAILED - $DATE" 2>&1; then
        echo "✅ Failure notification sent successfully"
        exit 0
    else
        echo "❌ Failed to send failure notification"
        exit 1
    fi
else
    echo "⚠️  Email sender not found: $SEND_EMAIL_SCRIPT"
    echo "Notification saved to: $NOTIFICATION_FILE"
    cat "$NOTIFICATION_FILE"
    exit 1
fi
