#!/bin/bash
#
# Final Brief Validation Script
# Workflow-level validation before sending email
#

set -euo pipefail

FINAL_BRIEF="$1"
LOG_FILE="${2:-/dev/null}"

# Validation results
VALIDATION_PASSED=true
ISSUES=()
WARNINGS=()

log() {
    echo "[WORKFLOW-VALIDATOR] $1" | tee -a "$LOG_FILE"
}

# Check if file exists
if [ ! -f "$FINAL_BRIEF" ]; then
    echo "ERROR: Final brief file not found: $FINAL_BRIEF"
    exit 1
fi

log "Starting workflow-level validation..."
log "Final brief: $FINAL_BRIEF"

BRIEF_CONTENT=$(cat "$FINAL_BRIEF")

# Validation 1: Check both major sections are present
log ""
log "CHECK 1: Major sections present"

if ! echo "$BRIEF_CONTENT" | grep -q "CoS BRIEF"; then
    ISSUES+=("Missing CoS BRIEF section")
    VALIDATION_PASSED=false
    log "  ❌ Missing CoS BRIEF section"
else
    log "  ✅ CoS BRIEF section present"
fi

if ! echo "$BRIEF_CONTENT" | grep -q "MARKET INTEL"; then
    ISSUES+=("Missing MARKET INTEL section")
    VALIDATION_PASSED=false
    log "  ❌ Missing MARKET INTEL section"
else
    log "  ✅ MARKET INTEL section present"
fi

# Validation 2: Check for minimum content length
log ""
log "CHECK 2: Content length validation"

LINE_COUNT=$(wc -l < "$FINAL_BRIEF")
WORD_COUNT=$(wc -w < "$FINAL_BRIEF")

if [ "$LINE_COUNT" -lt 50 ]; then
    ISSUES+=("Brief too short: $LINE_COUNT lines (expected >50)")
    VALIDATION_PASSED=false
    log "  ❌ Brief too short: $LINE_COUNT lines"
elif [ "$LINE_COUNT" -lt 80 ]; then
    WARNINGS+=("Brief is on the shorter side: $LINE_COUNT lines")
    log "  ⚠️  Brief is short: $LINE_COUNT lines"
else
    log "  ✅ Length acceptable: $LINE_COUNT lines, $WORD_COUNT words"
fi

# Validation 3: Check for broken/duplicate sections
log ""
log "CHECK 3: Section structure integrity"

# Check for duplicate headers (exact match with formatting)
DUPLICATE_COS=$(echo "$BRIEF_CONTENT" | grep -c "^CoS BRIEF —" || echo "0")
DUPLICATE_MARKET=$(echo "$BRIEF_CONTENT" | grep -c "^MARKET INTEL —" || echo "0")

if [ "$DUPLICATE_COS" -gt 1 ]; then
    ISSUES+=("Duplicate CoS BRIEF sections found ($DUPLICATE_COS)")
    VALIDATION_PASSED=false
    log "  ❌ Duplicate CoS BRIEF sections: $DUPLICATE_COS"
fi

if [ "$DUPLICATE_MARKET" -gt 1 ]; then
    ISSUES+=("Duplicate MARKET INTEL sections found ($DUPLICATE_MARKET)")
    VALIDATION_PASSED=false
    log "  ❌ Duplicate MARKET INTEL sections: $DUPLICATE_MARKET"
fi

if [ "$DUPLICATE_COS" -eq 1 ] && [ "$DUPLICATE_MARKET" -eq 1 ]; then
    log "  ✅ No duplicate sections"
fi

# Validation 4: Check for obvious errors or artifacts
log ""
log "CHECK 4: Error detection"

ERROR_PATTERNS=(
    "ERROR:"
    "FAILED:"
    "Exception:"
    "Traceback"
    "undefined"
    "null"
    "NaN"
)

for pattern in "${ERROR_PATTERNS[@]}"; do
    if grep -qi "$pattern" "$FINAL_BRIEF"; then
        ISSUES+=("Error marker found in brief: $pattern")
        VALIDATION_PASSED=false
        log "  ❌ Found error marker: $pattern"
    fi
done

log "  ✅ No error markers detected"

# Validation 5: Check for incomplete sections
log ""
log "CHECK 5: Section completeness"

# Each major section should have some content (not just headers)
COS_SECTION=$(sed -n '/CoS BRIEF/,/MARKET INTEL/p' "$FINAL_BRIEF" | wc -l)
MARKET_SECTION=$(sed -n '/MARKET INTEL/,/Generated by Claude/p' "$FINAL_BRIEF" | wc -l)

if [ "$COS_SECTION" -lt 20 ]; then
    ISSUES+=("CoS BRIEF section appears incomplete ($COS_SECTION lines)")
    VALIDATION_PASSED=false
    log "  ❌ CoS BRIEF section too short: $COS_SECTION lines"
else
    log "  ✅ CoS BRIEF section: $COS_SECTION lines"
fi

if [ "$MARKET_SECTION" -lt 15 ]; then
    ISSUES+=("MARKET INTEL section appears incomplete ($MARKET_SECTION lines)")
    VALIDATION_PASSED=false
    log "  ❌ MARKET INTEL section too short: $MARKET_SECTION lines"
else
    log "  ✅ MARKET INTEL section: $MARKET_SECTION lines"
fi

# Validation 6: Check for date consistency between sections
log ""
log "CHECK 6: Date consistency check"

# Extract dates from both sections
COS_DATE=$(sed -n '/CoS BRIEF/,/MARKET INTEL/p' "$FINAL_BRIEF" | grep -oE '[A-Z][a-z]+, [A-Z][a-z]+ [0-9]{1,2}' | head -1 || echo "")
MARKET_DATE=$(sed -n '/MARKET INTEL/,/Generated by/p' "$FINAL_BRIEF" | grep -oE '[A-Z][a-z]+, [A-Z][a-z]+ [0-9]{1,2}, [0-9]{4}' | head -1 || echo "")

if [ -n "$COS_DATE" ] && [ -n "$MARKET_DATE" ]; then
    # Dates should be within 1 day of each other
    log "  ✅ CoS date: $COS_DATE"
    log "  ✅ Market date: $MARKET_DATE"
else
    WARNINGS+=("Could not extract dates for consistency check")
    log "  ⚠️  Could not extract dates"
fi

# Validation 7: Check for generation timestamp
log ""
log "CHECK 7: Metadata validation"

if ! echo "$BRIEF_CONTENT" | grep -q "Generated by Claude"; then
    WARNINGS+=("Missing generation metadata")
    log "  ⚠️  Missing generation metadata"
else
    log "  ✅ Generation metadata present"
fi

# Validation 8: Check for common hallucination patterns
log ""
log "CHECK 8: Hallucination pattern detection"

HALLUCINATION_INDICATORS=(
    "I don't have access to"
    "I cannot access"
    "As an AI"
    "I apologize"
    "I'm sorry"
    "I don't actually"
    "I should clarify"
)

HALLUCINATION_FOUND=false
for pattern in "${HALLUCINATION_INDICATORS[@]}"; do
    if grep -qi "$pattern" "$FINAL_BRIEF"; then
        ISSUES+=("AI artifact detected in brief: $pattern")
        VALIDATION_PASSED=false
        HALLUCINATION_FOUND=true
        log "  ❌ AI artifact found: $pattern"
    fi
done

if [ "$HALLUCINATION_FOUND" = false ]; then
    log "  ✅ No AI artifacts detected"
fi

# Summary
log ""
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "WORKFLOW VALIDATION SUMMARY"
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

if [ ${#WARNINGS[@]} -gt 0 ]; then
    log ""
    log "⚠️  Warnings:"
    for warning in "${WARNINGS[@]}"; do
        log "  - $warning"
    done
fi

if [ "$VALIDATION_PASSED" = true ]; then
    log ""
    log "✅ Final Brief PASSED workflow validation"
    exit 0
else
    log ""
    log "❌ Final Brief FAILED workflow validation"
    log ""
    log "Issues found:"
    for issue in "${ISSUES[@]}"; do
        log "  - $issue"
    done
    exit 1
fi
